version: 2.1
jobs: 
  build: 
    docker:
      - image: circleci/node:lts
    environment:
      # Variables used in build steps
      # from https://developer.salesforce.com/tools/sfdxcli
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      - TESTLEVEL: RunLocalTests
      - DEPLOYDIR: src
    steps:
      - checkout
      - run:
          name: "Create SFDX Folder" 
          command: |
            # Create sfdx directory
            mkdir ~/sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            # By default, the script installs the current version of Salesforce CLI. To install the release candidate, set the DX_CLI_URL_CUSTOM local variable to the appropriate URL
            wget -qO- ${DX_CLI_URL_CUSTOM-$DX_CLI_URL} | tar xJ -C ~/sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            export PATH=~/sfdx/bin:$PATH
            echo "export PATH=~/sfdx/bin:$PATH" >> $BASH_ENV
            sfdx
      #- run:
      #    name: Decrypt server key
      #    command: |
           #Decrypt server key
      #      openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/servers.pass.key -base64 -K $SFDX_JWT_KEY -iv $DECRYPTION_IV
      - run:
          name: Authorize Target Deployment Org
          command: |
            #Authorize target org
            sfdx auth:jwt:grant --instanceurl login.salesforce.com  --clientid 3MVG9G9pzCUSkzZvY.1HulJWPyZvmC8s1v3Qn4hpG01LJXumOzpCpimNtP0SJR_xXz2chnBgaWRk2FoPLrYtS --jwtkeyfile assets/servers.pass.key --username $USER_NAME --setalias TEST
      - run:
          name: Deploy to Target Deployment Org
          command: |
            #Deploy to target deployment org and run unit tests. 
            sfdx force:mdapi:deploy --wait 10 --deploydir assets --targetusername TEST --testlevel $TESTLEVEL
            
            #Example shows how to run a check only deploy.
            #sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir assets --targetusername TEST --testlevel $TESTLEVEL
