public class JSONWrapper {
    
    public class result
       {  
          public String status; 
          public data[] data;
       }
    public class data
       {
          public Integer id;
          public String  employee_name;
          public String employee_salary;
          public String employee_age;
          public String profile_image;
          
       }

}





   /*  public String name;
        public String message;
        public Integer code;
        public Integer status;
        
    }*/